# Language classes containing dictionnary to scrap data, save and access it in all TCG languages


class Language():

	def __init__(self):

		self.all_language_code = ['fr', 'en', 'de', 'es', 'it', 'pt']
		self.words = dict()

class French(Language):

	def __init__(self):

		super().__init__()
		self.language = 'fr'
		self.web_dict = {
			'attribute': 'Attribut',
			'level': 'Niveau',
			'rank': 'Rang',
			'link': 'Lien',
			'type': 'Type de Carte',
			'icon': 'Icône',
			'race': 'Type de Monstre',
			'atk': 'ATK',
			'def': 'DEF',
			'scale': 'Échelle Pendule',
			'pendulum_effect': 'Effet Pendule',
			'description': 'Texte de Carte',
		}
		self.rar_dict = {
			'Gold Rare Premium': 'PGR',
			'Ultra Rare': 'UR',
			'Commun': 'C',
			'Commune': 'C',
			'Secrète Rare': 'ScR',
			'Gold Rare': 'GR',
			'Gold Secrète': 'GScR',
			'Ghost Rare': 'GR',
			'Super Rare': 'SR',
			'Shatterfoil': 'SHR',
			'Rare': 'R',
			'unknown': '?',
			'Secrète Rare Prismatique': 'PScR',
			'Ultime Rare': 'UtR',
			'Ultra Rare (Pharaonique Rare)': 'UR(PR)',
			'Starfoil': 'SFR',
			'COLLECTOR RARE': 'CR',
			'Starlight Rare': 'StR',
			'SECRÈTE RARE 10 000': '10000ScR',
			'Platinium Secrète Rare': 'PlScR'
		}

class English(Language):

	def __init__(self):

		super().__init__()
		self.language = 'en'
		self.web_dict = {
			'attribute': 'Attribute',	
			'level': 'Level',
			'rank': 'Rank',
			'link': 'Link',
			'type': 'Card Type',
			'spell': 'Spell',
			'trap': 'Trap',
			'icon': 'Icon',
			'race': 'Monster Type',
			'atk': 'ATK',
			'def': 'DEF',
			'scale': 'Pendulum Scale',
			'pendulum_effect': 'Pendulum Effect',
			'description': 'Card Text',
		}
		self.rar_dict = {
			'Premium Gold Rare': 'PGR',
			'Ultra Rare': 'UR',
			'Common': 'C',
			'Secret Rare': 'ScR',
			'Gold Rare': 'GR',
			'Gold Secret': 'GScR',
			'Ghost Rare': 'GR',
			'Super Rare': 'SR',
			'Shattefoil': 'SHR',
			'Rare': 'R',
			'Hobby': 'H',
			'unknown': '?',
			'Prismatic Secret Rare': 'PScR',
			'Ultimate Rare': 'UtR',
			'Ultra Rare (Pharaoh\'s Rare)': 'UR(PR)',
			'Starfoil': 'SFR',
			'COLLECTOR\'S RARE': 'CR',
			'Starlight Rare': 'StR',
			'10000 SECRET RARE': '10000ScR',
			'Platinum Secret Rare': 'PlScR',
			'Holographic Rare': 'HGR',
			'Platinum Rare': 'PlR',
			'Extra Secret Rare': 'EScR',
			'Ultra Secret Rare': 'UScR',
			'Mosaic Rare': 'MSR',

		}


class German(Language):

	def __init__(self):

		super().__init__()
		self.language = 'de'
		self.web_dict = {
			'attribute': 'Eigenschaft ',	
			'level': 'Stufe',
			'rank': 'Rang',
			'link': 'Link',
			'type': 'Kartentyp',
			'spell': 'Zauber',
			'trap': 'Fallen',
			'icon': 'Symbol',
			'race': 'Monstertyp',
			'atk': 'ATK',
			'def': 'DEF',
			'scale': 'Pendelbereich',
			'pendulum_effect': 'Pendeleffekt',
			'description': 'Kartentext',
		}
		self.rar_dict = {
			'Premium Gold Rare': 'PGR',
			'Ultra Rare': 'UR',
			'Common': 'C',
			'Secret Rare': 'ScR',
			'Gold Rare': 'GR',
			'Gold Secret': 'GScR',
			'Ghost Rare': 'GR',
			'Super Rare': 'SR',
			'Shatterfoil': 'SHR',
			'Rare': 'R',
			'Hobby': 'H',
			'unknown': '?',
			'Prismatic Secret Rare': 'PScR',
			'Ultimate Rare': 'UtR',
			'Ultra Rare (Pharaoh\'s Rare)': 'UR(PR)',
			'Starfoil': 'SFR',
			'COLLECTOR\'S RARE': 'CR',
			'Starlight Rare': 'StR',
			'10000 SECRET RARE': '10000ScR',
			'Platinum Secret Rare': 'PlScR',
			'Holographic Rare': 'HGR',
			'Platinum Rare': 'PlR',
			'Extra Secret Rare': 'EScR',
			'Ultra Secret Rare': 'UScR',
			'Mosaic Rare': 'MSR',

		}


class Spanich(Language):

	def __init__(self):

		super().__init__()
		self.language = 'es'
		self.web_dict = {
			'attribute': 'Atributo',	
			'level': 'Nivel',
			'rank': 'Rango',
			'link': 'Enlace',
			'type': 'Tipo de Carta',
			'spell': 'Mágica',
			'trap': 'Trampa',
			'icon': 'Ícono',
			'race': 'Tipo de Monstruo',
			'atk': 'ATK',
			'def': 'DEF',
			'scale': 'Escala de Péndulo',
			'pendulum_effect': 'Efecto de Péndulo',
			'description': 'Texto de la Carta',
		}
		self.rar_dict = {
			'Rara Dorada Premium': 'PGR',
			'Ultra Rara': 'UR',
			'Comune': 'C',
			'Rara Secreta': 'ScR',
			'Rara Dorada': 'GR',
			'Secreta Dorada': 'GScR',
			'Rara Fantasmal': 'GR',
			'Súper Rara': 'SR',
			'Shatterfoil': 'SHR',
			'Rara': 'R',
			'Hobby': 'H',
			'unknown': '?',
			'Rara Secreta Prismática': 'PScR',
			'Rara Definitiva': 'UtR',
			'Ultra Rara (Rara de Faraón)': 'UR(PR)',
			'Starfoil': 'SFR',
			'RARA DE COLECCIONISTA': 'CR',
			'Starlight Rare': 'StR',
			'10000 RARA SECRETA': '10000ScR',
			'Secreta Rara de Platino': 'PlScR',
			'Holographic Rare': 'HGR',
			'Platinum Rare': 'PlR',
			'Extra Secret Rare': 'EScR',
			'Ultra Secret Rare': 'UScR',
			'Mosaic Rare': 'MSR',

		}



class Italian(Language):

	def __init__(self):

		super().__init__()
		self.language = 'it'
		self.web_dict = {
			'attribute': 'Attributo',	
			'level': 'Livello',
			'rank': 'Rango',
			'link': 'Link',
			'type': 'Tipo di Carta',
			'spell': 'Magia',
			'trap': 'Trappola',
			'icon': 'Icona',
			'race': 'Tipo di Mostro',
			'atk': 'ATK',
			'def': 'DEF',
			'scale': 'Valore Pendulum',
			'pendulum_effect': 'Effetto Pendulum',
			'description': 'Testo Carta',
		}
		self.rar_dict = {
			'Rara Oro Premium': 'PGR',
			'Ultra Rara': 'UR',
			'Comuni': 'C',
			'Rara Segreta': 'ScR',
			'Rara Oro': 'GR',
			'Segreta Oro': 'GScR',
			'Rara Ghost': 'GR',
			'Super Rara': 'SR',
			'Shatterfoil': 'SHR',
			'Rara': 'R',
			'Hobby': 'H',
			'unknown': '?',
			'Rara Segreta Prismatica': 'PScR',
			'Rara Ultimate': 'UtR',
			'Ultra Rara (Rara del Faraone)': 'UR(PR)',
			'Starfoil': 'SFR',
			'RARA DA COLLEZIONE': 'CR',
			'Starlight Rare': 'StR',
			'RARA SEGRETA 10000': '10000ScR',
			'Rara Segreta Platino': 'PlScR',
			'Holographic Rare': 'HGR',
			'Platinum Rare': 'PlR',
			'Extra Secret Rare': 'EScR',
			'Ultra Secret Rare': 'UScR',
			'Mosaic Rare': 'MSR',

		}


class Portuguese(Language):

	def __init__(self):

		super().__init__()
		self.language = 'pt'
		self.web_dict = {
			'attribute': 'Atributo',	
			'level': 'Nível',
			'rank': 'Classe',
			'link': 'Link',
			'type': 'Tipo de Card',
			'spell': 'Magia',
			'trap': 'Armadilha',
			'icon': 'Ícone',
			'race': 'Tipo de Monstro',
			'atk': 'ATK',
			'def': 'DEF',
			'scale': 'Escala de Pêndulo',
			'pendulum_effect': 'Efeito de Pêndulo',
			'description': 'Texto do Card',
		}
		self.rar_dict = {
			'Rara Dourada Premium': 'PGR',
			'Ultra Rara': 'UR',
			'Comun': 'C',
			'Rara Secreta': 'ScR',
			'Rara Dourada': 'GR',
			'Secreta Dourada': 'GScR',
			'Rara Fantasma': 'GR',
			'Super Rara': 'SR',
			'Shatterfoil': 'SHR',
			'Starfoil': 'SFR',
			'Rara': 'R',
			'Hobby': 'H',
			'unknown': '?',
			'Rara Secreta Prismática': 'PScR',
			'Ultimate Rara': 'UtR',
			'Ultra Rara (Rara do Faraó)': 'UR(PR)',
			'Metalizadas-Estilhaçadas': 'SFR',
			'RARA DE COLECIONADOR': 'CR',
			'Starlight Rare': 'StR',
			'RARA SECRETA 10000': '10000ScR',
			'Rara Platina Secreta': 'PlScR',
			'Holographic Rare': 'HGR',
			'Rara Platina': 'PlR',
			'Extra Secret Rare': 'EScR',
			'Ultra Secret Rare': 'UScR',
			'Rara Mosaica': 'MSR',
			'': '?',

		}

# arch = {
# 	'Blue-Eyes': 'Yeux BLeus',
# 	'Battleguard': 'Guardes',
# 	'Magician': 'Magicien',
# 	'Exodia': 'Exodia',
# 	'Archfiend': 'Archdémon',
# 	'Worm': 'Vers',
# 	'Skull Servant': 'Crâne Serviteur',
# 	'Dark Magician': 'Magicien Sombre',
# 	'Gaia The Fierce Knight': 'Gaïa le Chevalier Implacable',
# 	'Celtic Guard': 'Guardien Celte',
# 	'Kuriboh': 'Kuriboh',
# 	'Shark': 'Requin',
# 	'Harpie': 'Harpie',
# 	'Red-Eyes': 'Yeux Rouges',
# 	'Mask': 'Masque',
# 	'Angel': 'Ange',
# 	'Penguin': 'Pingouin',
# 	'Madoor': 'Madoor',
# 	'D.D.': 'D.D.',
# 	'Slime': 'Slime',
# 	'Book of': 'Livre de',
# 	'Umi': 'Umi',
# 	'Hole': 'Trappe',
# 	'Black Luster Soldier': 'Soldat du Lustre Noir',
# 	'Guardian': 'Guardien',
# 	'Alligator': 'Alligator',
# 	'Toon': 'Toon',
# 	'Karakuri': 'Karakuri',
# 	'Thunder Dragon': 'Dragon du Tonerre',
# 	'Ninja': 'Ninja',
# 	'Rose Dragon': 'Dragon Rose',
# 	'Eyes Restrict': 'Renoncé aux Yeux',
# 	'Magnet Warrior': 'Guerrier Magnétique',
# 	'Jester': 'Bouffon',
# 	'Jinzo': 'Jinzo',
# 	'Parasite': 'Parasite',	
# 	'Anti': 'Anti',
# 	'Greed',
# 	'Solemn': 'Solennel',
# 	"Gravekeeper's": 'Protecteurs du Tombeau',
# 	'Nimble': 'Agile',
# 	'Egyptian God': 'Dieu Egyptien',
# 	'Parshath': 'Parshath',
# 	'Gadget': 'Gadget',
# 	'Spirit Message': 'Message Spirituel',
# 	'Earthbound': 'Esprit de la Terre',
# 	'Amazoness': 'Amazonesse',
# 	'Grepher': 'Grepher',
# 	'Vampire': 'Vampire',
# 	'Sphinx': 'Sphinx',
# 	'Dice': 'Dé',
# 	'Dark Scorpion': 'Scorpion Noir',
# 	'Roid': 'Roïd',
# 	'Knight': 'Chevalier',
# 	'ABC': 'ABC',
# 	'Dark World': 'Monde Ténébreux',
# 	'Chaos': 'Chaos',
# 	'Koala': 'Koala',
# 	'Maju': 'Maju',
# 	'Ojama': 'Ojama',	
# 	'The Agent': 'Agent',
# 	'Monarch': 'Monarche',
# 	'Gandora': 'Gandora',
# 	'Horus the Black Flame Dragon': 'Horus Dragon de la Flamme Noire',
# 	'Armed Dragon': 'Dragon Armé',
# 	'Silent Swordsman': 'Spadassin Silencieux',
# 	'Silent Magician': 'Magicien Silencieux',
# 	'Nephthys': 'Nephtys',
# 	'Machina': 'Machina',
# 	'Elemental HERO': 'HERO Elémentaire',
# 	'Ancient Gear': 'Rouages Anciens',
# 	'Charmer': 'Charmeuse',
# 	'Batteryman': 'Homme-Batterie',
# 	'Doriado': 'Doriado',
# 	'Cyber Dragon': 'Cyber Dragon',

# 	'Wicked God',
# 	'B.E.S.',
# 	'Frog',
# 	'Bonding',
# 	'Sacred Beast',
# 	'Photon',
# 	'Demise',
# 	'Destiny HERO',
# 	'Majestic',
# 	'Herald',
# 	'Simorgh',
# 	'Chrysalis',
# 	'Neo-Spacian',
# 	'Alien',
# 	'Volcanic',
# 	'Cyberdark',
# 	'Cyber Angel',
# 	'Allure Queen',
# 	'Six Samurai',
# 	'Spellbook',
# 	'Crystal Beast',
# 	'Blaze Accelerator',
# 	'Venom',
# 	'Bamboo Sword',
# 	'Fossil',
# 	'Evil HERO',
# 	'Cloudian',
# 	'Gladiator Beast',
# 	'Arcana Force',
# 	'Barbaros',
# 	'Atlantean',
# 	'Yubel',
# 	'Priestess',
# 	'Ice Barrier',
# 	'Mist Valley',
# 	'Flamvell',
# 	'X-Saber',
# 	'Ally of Justice',
# 	'Darklord',
# 	'Lightsworn',
# 	'Junk',
# 	'Synchron',
# 	'Resonator',
# 	'Stardust',
# 	'Genex',
# 	'Morphtronic',
# 	'Iron Chain',
# 	'Fabled',
# 	'Naturia',
# 	'Assault Mode',
# 	'Blackwing',
# 	'Jurrac',
# 	'Endymion',
# 	'Power Tool',
# 	'HERO',
# 	"Koa'ki Meiru",
# 	'Forbidden',
# 	'Infernity',
# 	'Fortune Lady',
# 	'Fishborg',
# 	'Dragunity',
# 	'Reptilianne',
# 	'Djinn',
# 	'Scrap',
# 	'Watt',
# 	'Malefic',
# 	'Gem-',
# 	'Laval',
# 	'Vylon',
# 	'Vision HERO',
# 	'Masked HERO',
# 	'Butterfly',
# 	'Gishki',
# 	'Gusto',
# 	'Steelswarm',
# 	'Infestation',
# 	'Noble Knight',
# 	'Meklord',
# 	'Nordic',
# 	'Symphonic Warrior',
# 	'Aesir',
# 	'T.G.',
# 	'Utopia',
# 	'Gagaga',
# 	'Gogogo',
# 	'Wind-Up',
# 	'Geargia',
# 	'Timelord',
# 	'Galaxy-Eyes',
# 	'Evolsaur',
# 	'Evolzar',
# 	'Evoltile',
# 	'Constellar',
# 	'Evilswarm',
# 	'Dododo',
# 	'Inzektor',
# 	'Ninjitsu Art',
# 	'Hieratic',
# 	'Bounzer',
# 	'Butterspy',
# 	'Hazy',
# 	'Gimmick Puppet',
# 	'Heroic',
# 	'Chronomaly',
# 	'Madolche',
# 	'Elemental Lord',
# 	'Heraldic',
# 	'Mermail',
# 	'Duston',
# 	'Heraldry',
# 	'Fire Fist',
# 	'Fire King',
# 	'Fire Formation',
# 	"Battlin' Boxer",
# 	'Mecha Phantom Beast',
# 	'CXyz',
# 	'Super Defense Robot',
# 	'Star Seraph',
# 	'Umbral Horror',
# 	'Bujin',
# 	'Traptrix',
# 	'Malicevorous',
# 	'Ghostrick',
# 	'Gorgonic',
# 	'Sylvan',
# 	'Artifact',
# 	'Odd-Eyes',
# 	'Aether',
# 	'Empowered Warrior',
# 	'Legendary Knight',
# 	'Performapal',
# 	'Superheavy',
# 	'Melodious',
# 	'Tellarknight',
# 	'Shaddoll',
# 	'Yang Zing',
# 	'Deskbot',
# 	'Stellarknight',
# 	'Vassal',
# 	'Burning Abyss',
# 	'U.A.',
# 	'D/D',
# 	'Edge Imp',
# 	'Fluffal',
# 	'Qli',
# 	'Apoqliphort',
# 	'Phantom Knights',
# 	'Dark Contract',
# 	'Yosenju',
# 	'Nekroz',
# 	'Ritual Beast',
# 	'Pendulum Dragon',
# 	'Raidraptor',
# 	'Infernoid',
# 	'Metaphys',
# 	'Hi-Speedroid',
# 	'Frightfur',
# 	'Clear Wing',
# 	'Zefra',
# 	'Performage',
# 	'Dracoslayer',
# 	'Igknight',
# 	'Aroma',
# 	'Prediction Princess',
# 	'Aquaactress',
# 	'Dracoverlord',
# 	'Majespecter',
# 	'Graydle',
# 	'Kozmo',
# 	'Kaiju',
# 	'PSY-Frame',
# 	'Paleozoic',
# 	'Destruction Sword',
# 	'Dinomist',
# 	'Shiranui',
# 	'Super Quant',
# 	'Lunalight',
# 	'Amorphage',
# 	'Digital Bug',
# 	'Magician Girl',
# 	'Metalfoes',
# 	'Triamid',
# 	'Cubic',
# 	'Cipher',
# 	'Flower Cardian',
# 	'Predaplant',
# 	'Crystron',
# 	'Chemicritter',
# 	'Subterror',
# 	'SPYRAL',
# 	'Abyss Actor',
# 	'Windwitch',
# 	'Zoodiac',
# 	'Shinobird',
# 	'Invoked',
# 	'Lyrilusc',
# 	'Supreme King',
# 	'True Draco',
# 	'Phantasm Spiral',
# 	'Code Talker',
# 	'Trickstar',
# 	'Gouki',
# 	'World Chalice',
# 	'World Legacy',
# 	'White',
# 	'Vendread',
# 	'F.A.',
# 	'Rokket',
# 	'Altergeist',
# 	'Krawler',
# 	'Borrel',
# 	'Secret Six Samurai',
# 	'Magical Musket',
# 	'The Weather',
# 	'Tindangle',
# 	'Mekk-Knight',
# 	'Knightmare',
# 	'Elementsaber',
# 	'Fur Hire',
# 	'Sky Striker',
# 	'Lady of Lament',
# 	'Crusadia',
# 	'Impcantation',
# 	'Golden Castle of Stromberg',
# 	'Salamangreat',
# 	'Dinowrestler',
# 	'Orcust',
# 	'Danger!',
# 	'Valkyrie',
# 	'Prank-Kids',
# 	'Mayakashi',
# 	'Guardragon',
# 	'Speedroid',
# 	'Chaos Phantom',
# 	'Time Thief',
# 	'Infinitrack',
# 	'Witchcrafter',
# 	'Evil Eye',
# 	'Marincess',
# 	'Tenyi',
# 	'Fortune Fairy',
# 	'Battlewasp',
# 	'Unchained',
# 	'Starliege',
# 	'Gizmek',
# 	'Dream Mirror',
# 	'Boot-Up',
# 	'Mathmech',
# 	'Dragonmaid',
# 	'Generaider',
# 	'@Ignister',
# 	'Ancient Warriors',
# 	'Megalith',
# 	'Onomato',
# 	'Nemesys',
# 	'Deep Sea',
# 	'Cataclysmic',
# 	'Codebreaker',
# 	'Void',
# 	'Plunder Patroll',
# 	'Adamancipator',
# 	'Rikka',
# 	'Eldlich',
# 	'Golden Land',
# 	'Virtual World',
# 	'Dogmatika',
# 	'Melffy',
# 	'Potan',
# 	'Roland',
# 	'Rose',
# 	'Numeron',
# 	'Glacial Beast',
# 	'Appliancer',
# 	'Possessed',
# 	'Spiritual Art',
# 	'Tri-Brigade',
# 	'Dual Avatar',
# 	'Cupid',
# 	'Infernoble Knight',
# 	'Myutant',
# 	'Magistus',
# 	'Live Twin',
# 	'Evil Twin',
# 	'Drytron',
# 	'Springans',
# 	'S-Force',
# 	'Paladins of Dragons',
# 	'Trap Monster',
# 	'Fairy Tail',
# 	'Sunseed',
# 	'Sunvine',
# 	'Sunavalon',
# 	'Holy Knight',
# 	'Starry Knight',
# 	'Doll',
# 	'War Rock',
# 	'Materiactor',
# 	'ZEXAL',
# 	'Amazement',
# 	'Live☆Twin',
# 	'Sky Scourge',
# 	'Stigmata',
# 	'A.I.',
# 	'Attraction',
# 	'Abhyss',
# 	'Solfachord',
# 	'Ursarctic',
# 	'Despia',
# 	'Swordsoul',
# 	'Magikey',
# 	'Suship',
# 	'Mystical Beast of the Forest',
# 	'Stigmatika',
# 	'Synchro',
# 	'Pendulum',
# 	'Cyber',
# 	'Fleur',
# 	'roid',
# 	'Kragen',
# 	'Utopic',
# 	'Zexal',
# 	'Number',
# 	'Rank-Up-Magic',
# 	'Icejade',
# 	'Man-Eater Bug',
# 	'Evil★Twin',
# 	'Branded',
# 	'Floowandereeze',
# 	'Star',
# 	'Beetrooper',
# 	'P.U.N.K.',
# 	'Exorsister',
# 	'Brave Token',
# }